# -- Put here the new name if you want to override the release name.
nameOverride: ""

# -- Same as nameOverride but for the fullname.
fullnameOverride: ""

# -- Same as nameOverride but for the namespace.
namespaceOverride: ""

childshiftname: ""
domain: "" #example us-1.8aeyw69n.stakater.cloud
global:
  namespace: ""

prometheus:
  rules:
    endpointDown:
      enabled: true
    slowQuery:
      enabled: true
    errorCode:
      enabled: true
  slack:
    channel: childshift-slo-observability
    token: api_token
