# -- Put here the new name if you want to override the release name.
nameOverride: ""

# -- Same as nameOverride but for the fullname.
fullnameOverride: ""

# -- Same as nameOverride but for the namespace.
namespaceOverride: ""

cluster: "mothershift"
global:
  namespace: "stakater-grafana-operator"

prometheus:
  rules:
    endpointDown:
      enabled: true
    slowQuery:
      enabled: true
    errorCode:
      enabled: true
  slack:
    channel: slo-observability
    token: api_token

grafana:
  folder: "SLO Observability"
  instanceSelector:
    matchLabels:
      app: "grafana"           # ĐÚNG 100% VỚI CLUSTER CỦA BẠN
  datasources:
    - inputName: "datasource"
      datasourceName: prometheus
