apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  namespace: openshift-monitoring
  name: openshift-router-internal-healthz
spec:
  interval: 5s
  jobName: blackbox-exporter
  module: http_2xx
  prober:
    scheme: http
    url: prometheus-blackbox-exporter.openshift-monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - http://router-internal-default.openshift-ingress.svc.cluster.local:1936/healthz
      labels:
        app: openshift-router-internal
        health: healthz
        cluster: {{ .Values.cluster }}

