tenant:
  enabled: true
  name: minio
  serviceAccountName: minio-tenant
  consoleSecret: console-secret
  consoleReplica: 1
  credsSecret: minio-creds-secret
  requestAutoCert: false
  pools:
    servers: 2
    storageSize: 4Gi
    storageClassName: stakater
    volumesPerServer: 2

serviceAccount:
  enabled: true
  name: minio-tenant

rbac:
  enabled: true
  role:
    name: minio-tenant-role
  roleBinding:
    name: minio-tenant-binding

secret:
  enabled: true
  labels: 
    # key: value
  annotations: 
    # key: value
  files:    
  - name: console-secret
    data:
      CONSOLE_ACCESS_KEY: YWRtaW4=
      CONSOLE_PBKDF_PASSPHRASE: YWRtaW4=
      CONSOLE_PBKDF_SALT: YWRtaW4=
      CONSOLE_SECRET_KEY: YWRtaW4=
  - name: minio-creds-secret
    data:
      ## Access Key for MinIO Tenant
      accesskey: "bWluaW8="
      ## Secret Key for MinIO Tenant
      secretkey: "bWluaW8xMjM="


##########################################################
# SealedSecrets
##########################################################
sealedSecret:
  enabled: false
  labels: 
    # key: value
  annotations: 
    # key: value
  files:
  # - name: example
  #   encryptedData:
  #     name: AgBghrdepGMKmp/rdtJrkBv/CWpJbtmoMsbKQ7QiZZ2kUoLeeTbrDnhmJY03kWKkNW4kN/sQRf6r1vvBEaR4nkHt5f/ayAeaH3NveI3bdb0xv/svvWjyjehwqwr/kNEAVWxRoUij0Y7MyIEAr4hnV2UnrhgvcjPJLNA8bK6spA+kuT328Vpyceyvnm6yArNn1aYlEckaFHrnculHWRpG73iRYxS5GWAY7EdkLXx7OLLWoopHtLcupklYyPfraJzPvBNZ5/PsyjlUBvoQbGV3cZlrdEj1WHj2S1RQ13ddf2WGtMHmY83t9B3LFZAZuA7BBt4rjludbwQm3/tJ5Kas1dDsSIRIIF7MTeum9YfRB8XUz8IxVKQ/JDskeynrWe3VzN/3HFVnv9GGFy+BCVXZKVU/roIRancz+nXkyoOHS722ZpBi53dfLItoS5dG+0EzArMTQzK/KXHz3b1rxp5oWWDNt3WggTiSg2zwy5ZR8VV2ToTDof6UrFmbCZv/kKriyxbVSxIo3KFnvuRiUZ5MwC0TNut4mW3LKyJfHqkUuLa1mYV6tKF58qBnoj/+JaibAIBEudT9hms5U52p7/jKmgHuop7XPEsz4OVwER//Vbv7X6ctoXtyPu6mZyOfOyJHM8Qj/H7/gwMBYhZHQ96DWrVmZOsWSRpZGJni4Xm7rgt2cFj6UtWv6lvl8aOi/HSZVC3TwWZ9mQrk
