{{- if .Values.ksm.enabled }}
{{- if and ( .Values.prometheus.rules.clusterOperator.unavailableReplicas ) ( .Values.prometheus.rules.clusterOperator.unavailableReplicas.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rabbitmq-cluster-operator-unavailable-replicas
{{- if .Values.prometheus.rules.clusterOperator.unavailableReplicas.namespace  }}
  namespace: {{ .Values.prometheus.rules.clusterOperator.unavailableReplicas.namespace }}
{{- else }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
{{- end }}
  # If labels are defined in spec.ruleSelector.matchLabels of your deployed Prometheus object, make sure to include them here.
  labels:
    role: alert-rules
{{- if .Values.prometheus.rules.labels }}
{{- toYaml .Values.prometheus.rules.labels | nindent 4 }}
{{- end }}
spec:
  groups:
  - name: rabbitmq-cluster-operator
    rules:
    - alert: RabbitMQClusterOperatorUnavailableReplicas
      expr: |
        kube_deployment_status_replicas_unavailable{deployment="rabbitmq-cluster-operator"}
        >
        0
      for: 5m
      annotations:
        description: |
          `{{`{{ $value }}`}}` replicas are unavailable in Deployment `rabbitmq-cluster-operator`
          in namespace `{{`{{ $labels.namespace }}`}}`.
        summary: |
          There are pods that are either running but not yet available or pods that still have not been created.
          Check the status of the deployment: `kubectl -n {{`{{ $labels.namespace }}`}} describe deployment rabbitmq-cluster-operator`
          Check the status of the pod: `kubectl -n {{`{{ $labels.namespace }}`}} describe pod -l app.kubernetes.io/component=rabbitmq-cluster-operator`
      labels:
        rulesgroup: rabbitmq-operator
        severity: warning
{{- end }}
{{- end }}
